prefix = "!"
commands = ["guides"]

[[views]]
    name = "guides_view"
    base_component_domain_types = ['AGENT', 'MAP']

    [[views.components]]
        type = 'select'
        domain_type = 'AGENT'
        placeholder = 'Select an agent...'


[[agent_guides_data]]

    agent = 'Sova'
    [[agent_guides_data.map]]
        [[agent_guides_data.haven]]
            [[agent_guides_data.haven.lineups]]

                ability = 'Recon Bolt'

                [[agent_guides_data.haven.lineups.attack]]
                    [[agent_guides_data.haven.lineups.attack.a]]
                        [[agent_guides_data.haven.lineups.attack.a.backsite]]
                        [[agent_guides_data.haven.lineups.attack.a.short]]
                    [[agent_guides_data.haven.lineups.attack.b]]
                    [[agent_guides_data.haven.lineups.attack.c]]

                [[agent_guides_data.haven.lineups.defence]]
                    [[agent_guides_data.haven.lineups.defence.a]]
                    [[agent_guides_data.haven.lineups.defence.b]]
                    [[agent_guides_data.haven.lineups.defence.c]]
