prefix = "!"
commands = ["guides"]

[[views]]
view_type = "guides_view"
base_component_domain_types = [ "agent" ]

  [[views.components]]
  type = "select"
  domain_type = "agent"
  placeholder = "Select an agent..."

  [[views.components]]
  type = "select"
  domain_type = "map"
  placeholder = "Select a map..."

  [[views.components]]
  type = "select"
  domain_type = "guide"
  placeholder = "Select a guide..."

  [[views.components]]
  type = "select"
  domain_type = "ability"
  placeholder = "Select an ability..."

  [[views.components]]
  type = "select"
  domain_type = "guide"
  placeholder = "Select a guide..."

  [[views.components]]
  type = "select"
  domain_type = "side"
  placeholder = "Select a side..."

  [[views.components]]
  type = "select"
  domain_type = "area"
  placeholder = "Select an area..."



[[agent_guides_data]]
value = "Sova"

  [[agent_guides_data.maps]]
  value = "Haven"

    [[agent_guides_data.maps.guides]]
    value = "Lineups"

      [[agent_guides_data.maps.guides.abilities]]
      value = "Recon Bolt"

        [[agent_guides_data.maps.guides.abilities.sides]]
        value = "Attack"
        areas = [ "A", "B", "C", "Double Doors" ]

        [[agent_guides_data.maps.guides.abilities.sides]]
        value = "Defence"
        areas = [ "A", "B", "C", "Double Doors" ]
  [[agent_guides_data.maps]]
    value = "Bind"

      [[agent_guides_data.maps.guides]]
      value = "Lineups"

        [[agent_guides_data.maps.guides.abilities]]
        value = "Recon Bolt"

          [[agent_guides_data.maps.guides.abilities.sides]]
          value = "Attack"
          areas = [ "A", "B" ]

          [[agent_guides_data.maps.guides.abilities.sides]]
          value = "Defence"
          areas = [ "A", "B" ]


[[agent_guides_data]]
value = "Viper"

  [[agent_guides_data.maps]]
  value = "Bind"

    [[agent_guides_data.maps.guides]]
    value = "Lineups"

      [[agent_guides_data.maps.guides.abilities]]
      value = "Snakebite"

        [[agent_guides_data.maps.guides.abilities.sides]]
        value = "Attack"
        areas = [ "A", "B", "Hooqah" ]

        [[agent_guides_data.maps.guides.abilities.sides]]
        value = "Defence"
        areas = [ "A", "B", "Hooqah" ]
