prefix = "!"
commands = ["guides"]

[[views]]
view_type = "guides_view"
base_component_domain_types = [ "agent" ]
next_view = "pagination_view"

  [[views.components]]
  type = "select"
  domain_type = "agent"
  title = "**Select an agent:**"

  [[views.components]]
  type = "select"
  domain_type = "map"
  title = "**Select a map:**"

  [[views.components]]
  type = "select"
  domain_type = "ability"
  title = "**Select an ability:**"

  [[views.components]]
  type = "select"
  domain_type = "area"
  title = "**Select an area:**"

[[views]]
view_type = "pagination_view"
next_view = ""

[emojis]
Sova = "<:sovaguidesbot:1012819739569041408>"
Viper = "<:viperguidesbot:1012833353071874168>"
Fade = "<:fadeguidesbot:1013055517456859146>"
Recon_Bolt = "<:reconboltguidesbot:1012855624406683678>"
Shock_Dart = "<:shockdartguidesbot:1012855609164582962>"
Haunt = "<:hauntguidesbot:1013054262588223498>"
Snake_Bite = "<:snakebiteguidesbot:1013048295289012254>"
Poison_Cloud = "<:poisoncloudguidesbot:1013048729835671652>"

[[agent_guides_data]]
value = "Sova"

  [[agent_guides_data.maps]]
  value = "Haven"

    [[agent_guides_data.maps.abilities]]
    value = "Recon Bolt"
    areas = [ "A", "B", "C", "Garage" ]

  [[agent_guides_data.maps]]
  value = "Ascent"

    [[agent_guides_data.maps.abilities]]
    value = "Shock Dart"
    areas = [ "Mid" ]

    [[agent_guides_data.maps.abilities]]
    value = "Recon Bolt"
    areas = [ "A" ]

[[agent_guides_data]]
value = "Fade"

  [[agent_guides_data.maps]]
  value = "Haven"

    [[agent_guides_data.maps.abilities]]
    value = "Haunt"
    areas = [ "C"]

  [[agent_guides_data.maps]]
  value = "Icebox"

    [[agent_guides_data.maps.abilities]]
    value = "Haunt"
    areas = [ "A"]

  [[agent_guides_data.maps]]
  value = "Pearl"

    [[agent_guides_data.maps.abilities]]
    value = "Haunt"
    areas = [ "A", "Mid"]

  [[agent_guides_data.maps]]
  value = "Ascent"

    [[agent_guides_data.maps.abilities]]
    value = "Haunt"
    areas = [ "A"]

[[agent_guides_data]]
value = "Viper"

  [[agent_guides_data.maps]]
  value = "Haven"

    [[agent_guides_data.maps.abilities]]
    value = "Snake Bite"
    areas = [ "A", "B", "C"]

    [[agent_guides_data.maps.abilities]]
    value = "Poison Cloud"
    areas = ["A","C"]

  [[agent_guides_data.maps]]
  value = "Bind"

    [[agent_guides_data.maps.abilities]]
    value = "Snake Bite"
    areas = [ "A"]



