#!/bin/bash
sudo yum install python3.8
sudo yum -y install python3-pip
cd /home/ec2-user/valorant-guides-discord-bot
python3.8 -m venv venv
source venv/bin/activate
sudo python3 -m pip install -r requirements.txt