name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x ]
        app-name: ['valorant-guides-deploy']
        deployment-group: [ 'githubdeploy' ]
        repo: [ 'hypromerto/valorant-guides-discord-bot' ]

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1

      - name: Deploy to AWS
        run: |
          aws deploy create-deployment \
          --application-name ${{matrix.app-name}} \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --deployment-group-name ${{matrix.deployment-group}} \
          --description "GitHub Deployment for the ${{ matrix.app-name }}-${{github.sha}}" \
          --github-location repository=${{matrix.repo}},commitId=${{github.sha}}